USE ARAC_MUAYENE_SISTEMI;
CREATE TABLE ARAC_BILGISI
(
Plaka VARCHAR (10) NOT NULL,
Surucu_TCKN VARCHAR(11) NOT NULL,
Arac_Turu VARCHAR(10) NOT NULL,
Ruhsat_No VARCHAR (7) NOT NULL,
Trafik_Sigortasi CHAR,
Randevu_No VARCHAR (10) NOT NULL,
PRIMARY KEY (Plaka),
FOREIGN KEY(Arac_Turu) REFERENCES ARAC_TURU(Arac_Tur_No),
FOREIGN KEY(Surucu_TCKN) REFERENCES ARAC_SAHIBI(TCKN),
FOREIGN KEY(Randevu_No) REFERENCES RANDEVU(Randevu_No)

);