USE ARAC_MUAYENE_SISTEMI;
CREATE TABLE RANDEVU
(
	Randevu_No VARCHAR (10) NOT NULL,
	Hizmet VARCHAR (10) NOT NULL,
	Istasyon VARCHAR (2) NOT NULL,
	Tarih DATE, 
PRIMARY KEY(Randevu_No),
FOREIGN KEY(Istasyon)REFERENCES SEHIRLER (Sehir_No),
FOREIGN KEY(Hizmet)REFERENCES HIZMET (Hizmet_No)
);