SELECT ARAC_BILGISI.Ruhsat_No,RANDEVU.Tarih,SEHIRLER.SehirAdi
FROM ARAC_BILGISI,RANDEVU,SEHIRLER
WHERE ARAC_BILGISI.Randevu_No=RANDEVU.Randevu_No
AND RANDEVU.Istasyon=SEHIRLER.Sehir_No
AND ARAC_BILGISI.Ruhsat_No='4978';