SELECT ARAC_SAHIBI.Adi_Soyadi,ARAC_BILGISI.Ruhsat_No,ARAC_TURU.Arac_Turu
FROM ARAC_SAHIBI,ARAC_BILGISI,ARAC_TURU
WHERE ARAC_SAHIBI.TCKN=ARAC_BILGISI.Surucu_TCKN
AND ARAC_BILGISI.Arac_Turu=ARAC_TURU.Arac_Tur_No
AND ARAC_SAHIBI.Adi_Soyadi='Sinan DÖNGEL';