SELECT ARAC_BILGISI.Plaka,ARAC_SAHIBI.Adi_Soyadi,RANDEVU.Tarih
FROM ARAC_BILGISI,ARAC_SAHIBI,RANDEVU
WHERE ARAC_SAHIBI.TCKN=ARAC_BILGISI.Surucu_TCKN
AND ARAC_BILGISI.Randevu_No=RANDEVU.Randevu_No
AND ARAC_BILGISI.Plaka='25 CD 25';