SELECT RANDEVU.Randevu_No,HIZMET.Hizmet_Bedelý,SEHIRLER.SehirAdi
FROM RANDEVU,HIZMET,SEHIRLER
WHERE RANDEVU.Hizmet=HIZMET.Hizmet_No
AND RANDEVU.Istasyon=SEHIRLER.Sehir_No
AND RANDEVU.Randevu_No='27';
