SELECT ARAC_SAHIBI.Adi_Soyadi,ARAC_BILGISI.Trafik_Sigortasi,RANDEVU.Tarih,HIZMET.Hizmet_Turu
FROM ARAC_SAHIBI,ARAC_BILGISI,RANDEVU,HIZMET
WHERE ARAC_SAHIBI.TCKN=ARAC_BILGISI.Surucu_TCKN
AND ARAC_BILGISI.Randevu_No=RANDEVU.Randevu_No
AND RANDEVU.Hizmet=HIZMET.Hizmet_No
AND ARAC_SAHIBI.Adi_Soyadi='Furkan DUVARDELEN';