SELECT ARAC_BILGISI.Plaka,RANDEVU.Tarih,HIZMET.Hizmet_Bedelý,SEHIRLER.SehirAdi
FROM ARAC_BILGISI,RANDEVU,HIZMET,SEHIRLER
WHERE ARAC_BILGISI.Randevu_No=RANDEVU.Randevu_No 
AND RANDEVU.Hizmet=HIZMET.Hizmet_No
AND RANDEVU.Istasyon=SEHIRLER.Sehir_No
AND ARAC_BILGISI.Plaka='44 MHA 852';