SELECT ARAC_TURU.Arac_Turu,ARAC_BILGISI.Plaka,RANDEVU.Randevu_Saati,SEHIRLER.SehirAdi
FROM ARAC_TURU,ARAC_BILGISI,RANDEVU,SEHIRLER
WHERE ARAC_TURU.Arac_Tur_No=ARAC_BILGISI.Arac_Turu
AND ARAC_BILGISI.Randevu_No=RANDEVU.Randevu_No
AND RANDEVU.Istasyon=SEHIRLER.Sehir_No
AND ARAC_BILGISI.Plaka='25 CD 25';